import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

//components
import Navbar from "./components/navbar";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AP Score Calculator",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        <main className="relative h-screen bg-gradient-to-b from-cyan-600 to-green-400 container py-10 px-10 mx-0 min-w-full flex flex-col items-center">
        {children}
        </main>
      </body>
      <div className="relative bg-cyan-600 text-white">
        <p style={{fontSize: '18px'}}>This is technically still a work in progress so please be patient! Additionally, do NOT use this for final reference. I&apos;m not confident in this calculator&apos;s accuracy since dearest College Board doesn&apos;t officially release anything.</p>
        <p style={{fontSize: '18px'}}>Made by a sleep deprived Fred Han in 15 minutes. If you find bugs email yhan84273 (at) tutanota (dot) com (Replies not guaranteed).</p>
      </div>
    </html>
  );
}
